namespace ApiWeld.Generator;

/// <summary>Writes generated files to disk.</summary>
public static class OutputWriter
{
	/// <summary>The first line of every generated file; only files carrying it are ever replaced or deleted.</summary>
	public const string Marker = "// <auto-generated/>";
}
