using System.Text;

namespace ApiWeld.Generator;

/// <summary>Writes generated files, replacing and removing only files it generated itself.</summary>
/// <remarks>See README.md, "Output".</remarks>
public static class OutputWriter
{
	/// <summary>The first line of every generated file.</summary>
	public const string Marker = "// <auto-generated/>";

	/// <summary>The second line of every generated file; only files starting with <see cref="Marker"/> and this line are ever replaced or deleted.</summary>
	public const string Signature = "// Generated by apiweld generate. Do not edit; regenerate instead.";

	static readonly UTF8Encoding Utf8WithBom = new(encoderShouldEmitUTF8Identifier: true);

	/// <summary>Writes <paramref name="files"/> under <paramref name="directory"/>; returns errors and writes nothing when a target was not generated.</summary>
	public static IReadOnlyList<Diagnostic> Write(string directory, IReadOnlyList<GeneratedFile> files)
	{
		var root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(directory)) + Path.DirectorySeparatorChar;
		var targets = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
		var errors = new List<Diagnostic>();

		foreach (var file in files)
		{
			var target = Path.GetFullPath(Path.Combine(root, file.Path));

			if (!target.StartsWith(root, StringComparison.OrdinalIgnoreCase))
				errors.Add(new(Severity.Error, $"{file.Path}: lies outside the output folder."));
			else if (!targets.TryAdd(target, file.Content))
				errors.Add(new(Severity.Error, $"{file.Path}: names the same file as another output path, differing only in case."));
		}

		errors.AddRange(targets.Keys
			.Where(File.Exists)
			.Where(target => !IsGenerated(target))
			.Order(StringComparer.Ordinal)
			.Select(target => new Diagnostic(Severity.Error, $"{target}: exists and was not generated; move it out of the output folder.")));

		if (errors.Count > 0)
			return errors;

		foreach (var (target, content) in targets)
		{
			Directory.CreateDirectory(Path.GetDirectoryName(target)!);
			var bytes = Utf8WithBom.GetPreamble().Concat(Utf8WithBom.GetBytes(content)).ToArray();

			if (!File.Exists(target) || !File.ReadAllBytes(target).AsSpan().SequenceEqual(bytes))
				File.WriteAllBytes(target, bytes);
		}

		if (Directory.Exists(directory))
			foreach (var stale in Directory.EnumerateFiles(directory, "*.g.cs", SearchOption.AllDirectories)
				.Where(file => !targets.ContainsKey(Path.GetFullPath(file)) && IsGenerated(file))
				.ToList())
				File.Delete(stale);

		return errors;
	}

	static bool IsGenerated(string path)
	{
		using var reader = new StreamReader(path, detectEncodingFromByteOrderMarks: true);

		return reader.ReadLine() == Marker && reader.ReadLine() == Signature;
	}
}
