using System.Text;

using ApiWeld.Generator;

namespace ApiWeld.Tests.Generator;

public class OutputWriterTests : IDisposable
{
	readonly string folder = Directory.CreateTempSubdirectory("apiweld-out").FullName;

	public void Dispose() => Directory.Delete(folder, recursive: true);

	const string Header = OutputWriter.Marker + "\n" + OutputWriter.Signature + "\n";

	static GeneratedFile Generated(string path) => new(path, Header + "class A { }\n");

	string At(string relative) => Path.Combine(folder, relative);

	void Put(string relative, string content)
	{
		Directory.CreateDirectory(Path.GetDirectoryName(At(relative))!);
		File.WriteAllText(At(relative), content);
	}

	[Fact]
	public void Writes_each_file_with_a_byte_order_mark()
	{
		Assert.Empty(OutputWriter.Write(folder, [Generated("Models/A.g.cs")]));

		var bytes = File.ReadAllBytes(At("Models/A.g.cs"));

		Assert.Equal(new byte[] { 0xEF, 0xBB, 0xBF }, bytes[..3]);
		Assert.Equal(Generated("Models/A.g.cs").Content, Encoding.UTF8.GetString(bytes[3..]));
	}

	[Fact]
	public void Deletes_stale_generated_files_and_keeps_everything_else()
	{
		Put("Models/Old.g.cs", Header);
		Put("Models/Hand.g.cs", "// mine\n");
		Put("Notes.txt", "keep");

		OutputWriter.Write(folder, [Generated("Models/A.g.cs")]);

		Assert.False(File.Exists(At("Models/Old.g.cs")));
		Assert.True(File.Exists(At("Models/Hand.g.cs")));
		Assert.True(File.Exists(At("Notes.txt")));
	}

	[Fact]
	public void Refuses_to_overwrite_a_file_it_did_not_generate()
	{
		Put("Models/A.g.cs", "// mine\n");

		var diagnostics = OutputWriter.Write(folder, [Generated("Models/A.g.cs"), Generated("Models/B.g.cs")]);

		var error = Assert.Single(diagnostics);
		Assert.Equal(Severity.Error, error.Severity);
		Assert.Contains("A.g.cs", error.Message);
		Assert.Equal("// mine\n", File.ReadAllText(At("Models/A.g.cs")));
		Assert.False(File.Exists(At("Models/B.g.cs")));
	}

	[Fact]
	public void Treats_a_file_from_another_generator_as_not_generated()
	{
		const string other = "// <auto-generated/>\n// Written by some other tool.\nclass B { }\n";
		Put("Models/Other.g.cs", other);
		Put("Models/A.g.cs", other);

		var diagnostics = OutputWriter.Write(folder, [Generated("Models/A.g.cs")]);

		Assert.Contains("A.g.cs", Assert.Single(diagnostics).Message);
		Assert.Equal(other, File.ReadAllText(At("Models/A.g.cs")));

		File.Delete(At("Models/A.g.cs"));
		Assert.Empty(OutputWriter.Write(folder, [Generated("Models/A.g.cs")]));

		Assert.Equal(other, File.ReadAllText(At("Models/Other.g.cs")));
	}

	[Fact]
	public void Refuses_a_relative_path_that_escapes_the_output_folder()
	{
		var diagnostics = OutputWriter.Write(Path.Combine(folder, "out"), [Generated("../escape.g.cs"), Generated("A.g.cs")]);

		var error = Assert.Single(diagnostics);
		Assert.Equal(Severity.Error, error.Severity);
		Assert.Contains("escape.g.cs", error.Message);
		Assert.False(File.Exists(At("escape.g.cs")));
		Assert.False(File.Exists(At("out/A.g.cs")));
	}

	[Fact]
	public void Refuses_a_sibling_folder_sharing_the_output_folders_prefix()
	{
		var diagnostics = OutputWriter.Write(Path.Combine(folder, "out"), [Generated("../out2/A.g.cs")]);

		Assert.Equal(Severity.Error, Assert.Single(diagnostics).Severity);
		Assert.False(File.Exists(At("out2/A.g.cs")));
	}

	[Fact]
	public void Refuses_an_absolute_path()
	{
		var absolute = At("elsewhere/A.g.cs");

		var diagnostics = OutputWriter.Write(Path.Combine(folder, "out"), [Generated(absolute)]);

		Assert.Equal(Severity.Error, Assert.Single(diagnostics).Severity);
		Assert.False(File.Exists(absolute));
	}

	[Fact]
	public void Refuses_two_paths_differing_only_in_case()
	{
		var diagnostics = OutputWriter.Write(folder, [Generated("Models/A.g.cs"), Generated("Models/a.g.cs")]);

		var error = Assert.Single(diagnostics);
		Assert.Equal(Severity.Error, error.Severity);
		Assert.Contains("a.g.cs", error.Message);
		Assert.False(Directory.Exists(At("Models")));
	}

	[Fact]
	public void Leaves_an_unchanged_file_untouched()
	{
		OutputWriter.Write(folder, [Generated("A.g.cs")]);
		var stamp = new DateTime(2020, 1, 1, 0, 0, 0, DateTimeKind.Utc);
		File.SetLastWriteTimeUtc(At("A.g.cs"), stamp);

		OutputWriter.Write(folder, [Generated("A.g.cs")]);

		Assert.Equal(stamp, File.GetLastWriteTimeUtc(At("A.g.cs")));
	}
}
